Repository argoproj/argo-events, pull requests merged in 2019-02, with the labels that each got.

#164 Ability to add timezone and extra user payload to calendar gateway
  gateways/core/calendar/config.go
  gateways/core/calendar/start.go
Labels: enhancement

#167 Enhance data filter
  docs/gateway-protocol.md
  docs/sensor-protocol.md
  examples/sensors/data-filter-webhook.yaml
  examples/sensors/time-filter-webhook.yaml
  examples/sensors/webhook-http-dependency-groups.yaml
  examples/sensors/webhook-nats.yaml
  examples/sensors/webhook-with-complete-payload.yaml
  examples/sensors/webhook-with-resource-param.yaml
  pkg/apis/common/generated.pb.go
  pkg/apis/gateway/v1alpha1/generated.pb.go
  pkg/apis/sensor/v1alpha1/generated.pb.go
  pkg/apis/sensor/v1alpha1/generated.proto
  pkg/apis/sensor/v1alpha1/openapi_generated.go
  pkg/apis/sensor/v1alpha1/types.go
  pkg/apis/sensor/v1alpha1/zz_generated.deepcopy.go
  sensors/event-handler.go
  sensors/signal-filter.go
  sensors/signal-filter_test.go
Labels: bug, enhancement

#168 Added support for backoff option when making connections in stream gw
  gateways/core/stream/amqp/config.go
  gateways/core/stream/amqp/start.go
  gateways/core/stream/kafka/config.go
  gateways/core/stream/kafka/start.go
  gateways/core/stream/mqtt/config.go
  gateways/core/stream/mqtt/start.go
  gateways/core/stream/nats/config.go
  gateways/core/stream/nats/start.go
  gateways/utils.go
Labels: enhancement

#170 Git as trigger source
  Gopkg.toml
  examples/sensors/trigger-source-git.yaml
  pkg/apis/common/generated.pb.go
  pkg/apis/gateway/v1alpha1/generated.pb.go
  pkg/apis/gateway/v1alpha1/openapi_generated.go
  pkg/apis/sensor/v1alpha1/generated.pb.go
  pkg/apis/sensor/v1alpha1/generated.proto
  pkg/apis/sensor/v1alpha1/openapi_generated.go
  pkg/apis/sensor/v1alpha1/types.go
  pkg/apis/sensor/v1alpha1/zz_generated.deepcopy.go
  sensors/trigger.go
  store/git.go
  store/store.go
Labels: enhancement

#172 Enhance github and gitlab gateway
  gateways/common/webhook.go
  gateways/community/aws-sns/validate.go
  gateways/community/github/config.go
  gateways/community/github/start.go
  gateways/community/github/validate.go
  gateways/community/github/validate_test.go
  gateways/community/gitlab/config.go
  gateways/community/gitlab/start.go
  gateways/community/gitlab/validate.go
  gateways/community/gitlab/validate_test.go
  gateways/community/storagegrid/start.go
  gateways/community/storagegrid/validate.go
  gateways/core/webhook/start.go
  gateways/core/webhook/validate.go
  store/store_test.go
Labels: enhancement

#182 modify instalation link
  CONTRIBUTING.md
Labels: documentation

#173 Fix typo in resource-gateway doc
  gateways/core/resource/install.md
Labels: documentation

#185 Fix resource gateway
  Gopkg.lock
  Makefile
  examples/gateways/aws-sns-gateway-configmap.yaml
  examples/gateways/aws-sns.yaml
  examples/gateways/resource-gateway-configmap.yaml
  examples/sensors/resource.yaml
  examples/sensors/webhook-http-boolean.yaml
  gateways/community/aws-sns/Dockerfile
  gateways/core/calendar/start.go
  gateways/core/resource/Dockerfile
  gateways/core/resource/start.go
Labels: bug

#180 Implement HDFS gateway
  DEPENDENCIES.md
  Gopkg.toml
  Makefile
  examples/gateways/hdfs-configmap.yaml
  examples/gateways/hdfs.yaml
  examples/sensors/hdfs.yaml
  gateways/common/naivewatcher/event.go
  gateways/common/naivewatcher/mutex.go
  gateways/common/naivewatcher/watcher.go
  gateways/common/naivewatcher/watcher_test.go
  gateways/community/hdfs/Dockerfile
  gateways/community/hdfs/client.go
  gateways/community/hdfs/cmd/main.go
  gateways/community/hdfs/config.go
  gateways/community/hdfs/start.go
  gateways/community/hdfs/validate.go
  gateways/community/hdfs/validate_test.go
Labels: enhancement
