Repository argoproj/argo-events, pull requests merged in 2019-03, with the labels that each got.

#189 adding code of conduct; moving assets into separate docs directory
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/architecture.png
  docs/assets/argo-events-logo.png
  docs/assets/argo-events-top-level.png
  docs/assets/communication.png
  docs/assets/custom-gateway.png
  docs/assets/gateways.png
  docs/assets/sensor.png
  docs/communication.md
  docs/gateway-guide.md
  docs/sensor-guide.md
Labels: documentation

#196 Update trigger guide
  docs/trigger-guide.md
  examples/sensors/trigger-gateway.yaml
  examples/sensors/trigger-standard-k8s-resource.yaml
Labels: documentation

#193 Trello gateway
  DEPENDENCIES.md
  Gopkg.lock
  Gopkg.toml
  Makefile
  examples/gateways/trello-gateway-configmap.yaml
  examples/gateways/trello.yaml
  examples/sensors/trello.yaml
  gateways/community/trello/Dockerfile
  gateways/community/trello/cmd/main.go
  gateways/community/trello/config.go
  gateways/community/trello/start.go
  gateways/community/trello/validate.go
  gateways/community/trello/validate_test.go
Labels: enhancement

#206 feature(): making webhook secure
  examples/gateways/secure-webhook-gateway-configmap.yaml
  examples/gateways/secure-webhook.yaml
  gateways/common/webhook.go
Labels: enhancement

#205 fix(): fix the git trigger branch or tag switch bug
  store/git.go
Labels: bug

#213 Improve file gateway
  examples/sensors/file.yaml
  examples/sensors/hdfs.yaml
  gateways/common/fsevent/fileevent.go
  gateways/common/naivewatcher/watcher.go
  gateways/common/naivewatcher/watcher_test.go
  gateways/community/hdfs/start.go
  gateways/community/hdfs/validate.go
  gateways/core/file/start.go
Labels: enhancement
